---
- hosts: nodes
  become: True  
  tasks: 
  - name: App
    become: True  
    docker:
      name: App
      image: thiagohara/chaordic-desafio2:latest
      #pull: always
      state: running
      restart_policy: always
      ports: 
        - "3000:3000"  